cache:
  paths:
    - node_modules/

stages:
 - build
 - test
 - deploy

test:
  stage: test
  tags:
    - development
  script:
    - npm run lint
    - npm run style
  only:
    - branches
    - tags
