<script src="//cdn.staticfile.org/vue/2.5.2/vue.min.js"></script>
<script src="//cdn.staticfile.org/vue-router/2.7.0/vue-router.min.js"></script>
<script src="//cdn.staticfile.org/vuex/3.0.0/vuex.min.js"></script>
<script src="//cdn.staticfile.org/jquery/3.3.1/jquery.min.js"></script>
<script src="//cdn.staticfile.org/lodash.js/4.17.11/lodash.min.js"></script>
<script src="//cdn.staticfile.org/element-ui/2.4.9/index.js"></script>
